version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=f2(8-sa(2cwfoy$trgp)(__esbfd*$$*6wgzum0@y9)nplk99#o
        # Double dollar $$ used to represent $ 
      - DEBUG=0
      - STRIPE_PUBLISHABLE_KEY=pk_test_51GtGlcEylJYmrPP4NTTVHyPpjPuzDniIYQguDWcyaROnp2T9cTm0N7oxkWOcPkIRG72AW1gJ2pMaDmjK95GYsrzw00zSevTkeB
      - STRIPE_SECRET_KEY_FILE=/run/secrets/stripe_secret_key
    secrets:
      - stripe_secret_key
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password_file
    secrets:
      - postgres_password_file
    ports:
      - 5432:5432

secrets:
  stripe_secret_key:
    file:
      stripe_secret_key.txt
  postgres_password_file:
    file:
      /secrets/djbookstore_postgres
