# Generated by Django 3.0.7 on 2020-06-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_statuses', 'Can read all books')]},
        ),
    ]
